#@data/values-schema
---
AWS_REGION: "changeme"
MGMT_CLUSTER_NAME: "changeme"
CLUSTER_NAME: "changeme"
AWS_VPC_ID: "changeme"
AWS_PRIVATE_SUBNET_ID: "changeme"
AWS_PUBLIC_SUBNET_ID:  "changeme"
AWS_SSH_KEY_NAME: "changeme"